all:
  hosts:
    mon:
      ansible_host: 147.75.39.207
    osd1:
      ansible_host: 147.75.77.91
    osd2:
      ansible_host: 147.75.98.219
  children:
    mons:
      hosts:
        mon:
    osds:
      hosts:
        osd1:
        osd2:
